[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://postgres:postgres@localhost:5432/postgres"
name = "dbconn"
default = true

[grid]
predefined = "web_mercator"

[[tileset]]
name = "ne_110m_admin_0_countries"
extent = [-180,-90,180,90]
minzoom = 0
maxzoom = 19

[[tileset.layer]]
# load data in db with:
# export PGPASSWORD=postgres;export PGCONN="PG:dbname='postgres' host='localhost' port='5433' user='postgres'";ogr2ogr -f PostgreSQL "$PGCONN" data/natural_earth.gpkg ne_110m_admin_0_countries
name = "ne_110m_admin_0_countries"
fid_field = "fid"
geometry_field = "geom"
geometry_type = "MULTIPOLYGON"
srid = 3857
buffer_size = 80
simplify = false
make_valid = true
table_name = "ne_110m_admin_0_countries"

[cache.s3]
# see README.md for instructions to setup local S3 service ("S3 tests")
endpoint = "http://localhost:9000"
bucket = "trex"
access_key = "miniostorage"
secret_key = "miniostorage"
region = "my-region"
key_prefix = "my-prefix"
baseurl = "https://localhost:9000/trex/my-prefix"

[webserver]
bind = "127.0.0.1"
port = 6767
